@url = http://localhost:3000/api
@id = 5b5ed8e33d9842242cad1164
@name = Product with reviews
@reviews = [{ "name": "Review 1" }, { "name": "Review 2" }]
@token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE1MzI5NDI1MjUsImV4cCI6MTUzNjU0MjUyNX0.FnPBQ4T3buvJog7LKgl4msfrhk6kUIGcNFlSXpPUjm1aDpApRNEDBqio7ub5a9Psw99aKO0IIQ7iq67pAQjbdA

GET {{url}}/products HTTP/1.1
Authorization: {{token}}

###
GET {{url}}/products/{{id}} HTTP/1.1
Authorization: {{token}}

###
GET {{url}}/products/{{id}}/reviews HTTP/1.1
Authorization: {{token}}

###
POST {{url}}/products HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
    "name": "{{name}}",
    "reviews": {{reviews}}
}

###
GET {{url}}/users HTTP/1.1
Authorization: {{token}}

###
POST {{url}}/auth/local HTTP/1.1
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}
